In [66]:


import numpy as np
from numpy.random import *
import math

count = 12
_lo = np.array(rand(count))
#_la = _lo**3 

lo = np.sort(_lo + 35) 
la = np.sort(_la + 139)
points_d = np.c_[lo, la]

In [67]:
points_d

array([[  35.04284278,  139.00009219],
       [  35.07055809,  139.01102332],
       [  35.20774397,  139.06712054],
       [  35.21460654,  139.08093342],
       [  35.31542717,  139.08189735],
       [  35.39273798,  139.41540726],
       [  35.40903135,  139.49514821],
       [  35.5936361 ,  139.55688541],
       [  35.6340929 ,  139.68057642],
       [  35.71916896,  139.77313011],
       [  35.97066384,  139.82231515],
       [  35.98158423,  139.95840422]])

In [68]:
35.99999512 - 0.03

35.96999512

In [69]:
139.99998537 - 0.03

139.96998537

In [71]:
endpoint = np.array([35.31542717, 139.08189735]).astype(float)

In [72]:
endpoint

array([  35.31542717,  139.08189735])

In [73]:
endpoint - points_d

array([[  2.72584390e-01,   8.18051573e-02],
       [  2.44869080e-01,   7.08740323e-02],
       [  1.07683201e-01,   1.47768105e-02],
       [  1.00820628e-01,   9.63930743e-04],
       [  9.57101065e-11,   2.46677700e-09],
       [ -7.73108069e-02,  -3.33509908e-01],
       [ -9.36041837e-02,  -4.13250860e-01],
       [ -2.78208927e-01,  -4.74988062e-01],
       [ -3.18665732e-01,  -5.98679067e-01],
       [ -4.03741788e-01,  -6.91232757e-01],
       [ -6.55236666e-01,  -7.40417796e-01],
       [ -6.66157056e-01,  -8.76506868e-01]])

In [74]:
endpoint - 0.03

array([  35.28542717,  139.05189735])

In [75]:
endpoint - 0.03 - points_d

array([[ 0.24258439,  0.05180516],
       [ 0.21486908,  0.04087403],
       [ 0.0776832 , -0.01522319],
       [ 0.07082063, -0.02903607],
       [-0.03      , -0.03      ],
       [-0.10731081, -0.36350991],
       [-0.12360418, -0.44325086],
       [-0.30820893, -0.50498806],
       [-0.34866573, -0.62867907],
       [-0.43374179, -0.72123276],
       [-0.68523667, -0.7704178 ],
       [-0.69615706, -0.90650687]])

In [76]:
(endpoint - 0.03 - points_d) < 0

array([[False, False],
       [False, False],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [77]:
points_d[:,1]

array([ 139.00009219,  139.01102332,  139.06712054,  139.08093342,
        139.08189735,  139.41540726,  139.49514821,  139.55688541,
        139.68057642,  139.77313011,  139.82231515,  139.95840422])

In [78]:
points_d[:,0]

array([ 35.04284278,  35.07055809,  35.20774397,  35.21460654,
        35.31542717,  35.39273798,  35.40903135,  35.5936361 ,
        35.6340929 ,  35.71916896,  35.97066384,  35.98158423])

In [79]:
endpoint[0] - points_d[:,0]

array([  2.72584390e-01,   2.44869080e-01,   1.07683201e-01,
         1.00820628e-01,   9.57101065e-11,  -7.73108069e-02,
        -9.36041837e-02,  -2.78208927e-01,  -3.18665732e-01,
        -4.03741788e-01,  -6.55236666e-01,  -6.66157056e-01])

In [80]:
endpoint[1] - points_d[:,1]

array([  8.18051573e-02,   7.08740323e-02,   1.47768105e-02,
         9.63930743e-04,   2.46677700e-09,  -3.33509908e-01,
        -4.13250860e-01,  -4.74988062e-01,  -5.98679067e-01,
        -6.91232757e-01,  -7.40417796e-01,  -8.76506868e-01])

In [81]:
np.square(endpoint[0] - points_d[:,0])

array([  7.43022498e-02,   5.99608664e-02,   1.15956718e-02,
         1.01647990e-02,   9.16042449e-21,   5.97696086e-03,
         8.76174320e-03,   7.74002072e-02,   1.01547849e-01,
         1.63007431e-01,   4.29335089e-01,   4.43765223e-01])

In [82]:
np.square(endpoint[1] - points_d[:,1])

array([  6.69208377e-03,   5.02312845e-03,   2.18354128e-04,
         9.29162477e-07,   6.08498879e-18,   1.11228859e-01,
         1.70776273e-01,   2.25613659e-01,   3.58416625e-01,
         4.77802725e-01,   5.48218513e-01,   7.68264291e-01])

In [83]:
np.sqrt(np.square(endpoint[0] - points_d[:,0]) + np.square(endpoint[1] - points_d[:,1]))

array([  2.84595034e-01,   2.54919585e-01,   1.08692345e-01,
         1.00825236e-01,   2.46863307e-09,   3.42353355e-01,
         4.23719266e-01,   5.50466953e-01,   6.78206808e-01,
         8.00506187e-01,   9.88713104e-01,   1.10092212e+00])

In [88]:
a = np.sqrt(np.square(endpoint[0] - points_d[:,0]) + np.square(endpoint[1] - points_d[:,1]))

In [90]:
a < 0.2

array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False], dtype=bool)

np.any(a < 0.2)

In [89]:
np.any(a < 0.2)

True